package com.sshex.sunrise.constant

const val SEARCH_CITY_ACTIVITY_REQUEST_CODE = 1000
const val LOCATION_PERMISSIONS_REQUEST = 1001
const val LOAD_COORDS_FAILED = 1002
const val LOAD_INFO_BY_COORDS_FAILED = 1003